// <auto-generated />
namespace GeLiData_WMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Change230306_03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change230306_03));
        
        string IMigrationMetadata.Id
        {
            get { return "202303061005583_Change230306_03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
