//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGVAlarmLog
    {
        public int ID { get; set; }
        public string deviceNum { get; set; }
        public string alarmDesc { get; set; }
        public Nullable<int> alarmType { get; set; }
        public Nullable<int> areaId { get; set; }
        public Nullable<int> alarmReadFlag { get; set; }
        public string channelDeviceId { get; set; }
        public string alarmSource { get; set; }
        public string channelName { get; set; }
        public Nullable<System.DateTime> alarmDate { get; set; }
        public System.DateTime recTime { get; set; }
        public string deviceName { get; set; }
        public Nullable<int> alarmGrade { get; set; }
    }
}
