//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceStatesInfo
    {
        public int ID { get; set; }
        public string deviceCode { get; set; }
        public string payLoad { get; set; }
        public string devicePostionRec { get; set; }
        public string devicePosition { get; set; }
        public string battery { get; set; }
        public string deviceName { get; set; }
        public Nullable<int> deviceStatusInt { get; set; }
        public string deviceStatus { get; set; }
        public System.DateTime recTime { get; set; }
        public string devicePostionX { get; set; }
        public string devicePostionY { get; set; }
    }
}
