//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int ID { get; set; }
        public string prosn { get; set; }
        public System.DateTime prodate { get; set; }
        public string proname { get; set; }
        public string itemno { get; set; }
        public int ProductOrderlistsID { get; set; }
        public string @class { get; set; }
        public string unit { get; set; }
        public string spec { get; set; }
        public string batchNo { get; set; }
        public string boxNo { get; set; }
        public string boxName { get; set; }
        public string ingredients { get; set; }
        public string remark1 { get; set; }
        public string protype { get; set; }
        public string color { get; set; }
        public string probiaozhun { get; set; }
        public string yuanliaobatchNo { get; set; }
        public string position { get; set; }
    
        public virtual ProductOrderlists ProductOrderlists { get; set; }
    }
}
