//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelenClients
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string levelCode { get; set; }
        public Nullable<System.DateTime> serverTime { get; set; }
        public string condiction { get; set; }
        public string remark { get; set; }
        public string fax { get; set; }
        public string address { get; set; }
        public string bank { get; set; }
        public string Eamil { get; set; }
        public string Number { get; set; }
        public string clientManager { get; set; }
        public string implementer { get; set; }
        public string gendan { get; set; }
        public string nickname { get; set; }
        public string openid { get; set; }
    }
}
