//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WareArea()
        {
            this.WareLocation = new HashSet<WareLocation>();
        }
    
        public int ID { get; set; }
        public string WareNo { get; set; }
        public Nullable<int> War_ID { get; set; }
        public Nullable<int> WareHouse_ID { get; set; }
        public Nullable<bool> WareAreaState { get; set; }
        public string protype { get; set; }
        public string InstockWay { get; set; }
        public string InstockRule { get; set; }
    
        public virtual WareAreaClass WareAreaClass { get; set; }
        public virtual WareHouse WareHouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WareLocation> WareLocation { get; set; }
    }
}
