//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WareLocation()
        {
            this.TrayState = new HashSet<TrayState>();
        }
    
        public int ID { get; set; }
        public string WareLocaNo { get; set; }
        public Nullable<int> WareArea_ID { get; set; }
        public Nullable<int> header_ID { get; set; }
        public Nullable<bool> WareLocaState { get; set; }
        public string AGVPosition { get; set; }
        public string WareLocaNo_Long { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrayState> TrayState { get; set; }
        public virtual Users Users { get; set; }
        public virtual WareArea WareArea { get; set; }
    }
}
